import request from 'supertest'
import app from '../app'
import { loginTest } from './login'
import { productTest } from './product'
import { categoryTest } from './category'
import { areaTest } from './area'
import { tableTest } from './table'

const tokenManager =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiJkZTAxNWFkNC1hYzcxLTExZWYtYjdiYS0wMjQyYWMxMjAwMDIiLCJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiIkMmEkMTIkUzAxS3J0OWcvWndRUFY1Y1B3U1ltT2F5aVNMVzBLQUtiTHRYa3J2cGhZS0pmODVGY1p2R3UiLCJyb2xlSWQiOiJiMzRmMmIyMi1hYzcxLTExZWYtYjdiYS0wMjQyYWMxMjAwMDIiLCJpc0FjdGl2ZSI6dHJ1ZSwiY3JlYXRlZEF0IjoiMjAyNC0xMS0yN1QwMzo0NDoxMi43NjhaIiwicm9sZSI6eyJuYW1lIjoiQURNSU4ifSwicHJvZmlsZSI6bnVsbCwiaWF0IjoxNzMzMzIwNjA3LCJleHAiOjE3MzMzMzg2MDd9.siMGlH7qB3IbwG2EfZufu_3sBJ3XNY61Y6UqLkkYzb8'
const tokenCheff = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiIzOWJkNzdmYi1hYzk2LTExZWYtOGQ1Yy0wMjQyYWMxMjAwMDIiLCJ1c2VybmFtZSI6ImEiLCJwYXNzd29yZCI6IiQyYiQxMCQyekdxakNKOURWb2dPalFDSXc0SkRPUFowL3c4dDFQMjJHVGh0eTNWQnd3SXJOSGJCS1BFcSIsInJvbGVJZCI6ImI4OWE0YTQ0LWFjNzEtMTFlZi1iN2JhLTAyNDJhYzEyMDAwMiIsImlzQWN0aXZlIjp0cnVlLCJjcmVhdGVkQXQiOiIyMDI0LTExLTI3VDA4OjA0OjI4LjU0OVoiLCJyb2xlIjp7Im5hbWUiOiJDSEVGRiJ9LCJwcm9maWxlIjp7InByb2ZpbGVJZCI6IjM5YzAxYWVjLWFjOTYtMTFlZi04ZDVjLTAyNDJhYzEyMDAwMiIsImZpcnN0TmFtZSI6ImEiLCJsYXN0TmFtZSI6ImEiLCJhZGRyZXNzIjoiYSIsInBob25lTnVtYmVyIjoiMSIsImNjY2QiOiIxIiwiYWNjb3VudElkIjoiMzliZDc3ZmItYWM5Ni0xMWVmLThkNWMtMDI0MmFjMTIwMDAyIiwiY3JlYXRlZEF0IjoiMjAyNC0xMS0yN1QwODowNDoyOC41NzNaIn0sImlhdCI6MTczMzMyMDgxOCwiZXhwIjoxNzMzMzM4ODE4fQ.FnE-6FOIvJzYDn9MdFZXV1OGHE2PjnzwwUotgUK781Q,'
const tokenStaff = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI3ZGQ4OWMxNS1hYzcyLTExZWYtYjdiYS0wMjQyYWMxMjAwMDIiLCJ1c2VybmFtZSI6InQiLCJwYXNzd29yZCI6IiQyYiQxMCQ5bmxPUW1kalRzLnpxRm1UZXNYRjVldm9KSEt6Qno5UXdCUXkwZkZvTHJncUFpaURXTzguQyIsInJvbGVJZCI6ImIwODc5MWQ0LWFjNzEtMTFlZi1iN2JhLTAyNDJhYzEyMDAwMiIsImlzQWN0aXZlIjp0cnVlLCJjcmVhdGVkQXQiOiIyMDI0LTExLTI3VDAzOjQ4OjQwLjkxM1oiLCJyb2xlIjp7Im5hbWUiOiJTVEFGRiJ9LCJwcm9maWxlIjp7InByb2ZpbGVJZCI6IjdkZGMwMzU1LWFjNzItMTFlZi1iN2JhLTAyNDJhYzEyMDAwMiIsImZpcnN0TmFtZSI6IlRvw6BuIiwibGFzdE5hbWUiOiJDaHVuZyIsImFkZHJlc3MiOiJBRyIsInBob25lTnVtYmVyIjoiMSIsImNjY2QiOiIxIiwiYWNjb3VudElkIjoiN2RkODljMTUtYWM3Mi0xMWVmLWI3YmEtMDI0MmFjMTIwMDAyIiwiY3JlYXRlZEF0IjoiMjAyNC0xMS0yN1QwMzo0ODo0MC45NTlaIn0sImlhdCI6MTczMzMyMDg0MywiZXhwIjoxNzMzMzM4ODQzfQ.o-WsSf_LP2tuBzYZ0ZlhhFCNZ055_r5N2onQiPPDPqU'
const tokenCustomer =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXN0b21lcklkIjoiNWJlMWNmNTAtYWM3My0xMWVmLWI3YmEtMDI0MmFjMTIwMDAyIiwiY3JlYXRlZEF0IjoiMjAyNC0xMS0yN1QwMzo1NDo1My40NTBaIiwicGhvbmVOdW1iZXIiOiIxMiIsIm5hbWUiOiJ0Iiwicm9sZSI6eyJuYW1lIjoiQ1VTVE9NRVIifSwiaWF0IjoxNzMzMzIwNzU3LCJleHAiOjE3MzMzMzg3NTd9.ezSzqyl2X0bDWqNy6wSZ7B6hsG4b4k7E37Y_THXn4TM'
describe('App Test Suite', () => {
  it('GET /health should return 200', async () => {
    const response = await request(app).get('/health')
    expect(response.status).toBe(200)
    expect(response.body).toEqual({ status: 'OK' })
  })
})
loginTest(request, app)
categoryTest(request, app, tokenManager, tokenCustomer)
areaTest(request, app, tokenManager, tokenCustomer)
tableTest(request, app, tokenManager, tokenCheff, tokenStaff)
productTest(request, app , tokenManager)
