services:
  mysql:
    image: mysql:8.0           # Sử dụng image MySQL phiên bản 8.0
    container_name: mysql_db    # Tên của container MySQL
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword   # Mật khẩu cho tài khoản root
      MYSQL_DATABASE: my_database         # Tên cơ sở dữ liệu mặc định
      MYSQL_USER: user                    # Tên người dùng mặc định
      MYSQL_PASSWORD: userpassword        # Mật khẩu cho người dùng
    ports:
      - "3306:3306"                       # Mở cổng 3306 cho MySQL
    volumes:
      - mysql_data:/var/lib/mysql         # Lưu trữ dữ liệu của MySQL

volumes:
  mysql_data:
    driver: local
